// <auto-generated />
using System;
using AstroColony.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AstroColony.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AstroColony.Entities.ItemEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConsumoMedioDiario")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("QuantidadeAtual")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("ItensEstoque");
                });

            modelBuilder.Entity("AstroColony.Entities.Tripulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Funcao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StatusSaude")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Tripulantes");
                });

            modelBuilder.Entity("AstroColony.Entities.ItemEstoque", b =>
                {
                    b.HasOne("AstroColony.Entities.Tripulante", "Responsavel")
                        .WithMany("ItensSobResponsabilidade")
                        .HasForeignKey("ResponsavelId");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("AstroColony.Entities.Tripulante", b =>
                {
                    b.Navigation("ItensSobResponsabilidade");
                });
#pragma warning restore 612, 618
        }
    }
}
